// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAPllxW76PdarRjm74Yy96rrvOHzILx_A',
    appId: '1:671878337704:web:6d1dfa22944e47579e5e9d',
    messagingSenderId: '671878337704',
    projectId: 'travel-list-29',
    authDomain: 'travel-list-29.firebaseapp.com',
    storageBucket: 'travel-list-29.appspot.com',
    measurementId: 'G-S7DQPBN2ZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYJwgVHXtYUOhBY16hStzUNxtI10diZPo',
    appId: '1:671878337704:android:7f7d5a1a00ba7a5c9e5e9d',
    messagingSenderId: '671878337704',
    projectId: 'travel-list-29',
    storageBucket: 'travel-list-29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwFp-phHGegV8pR1xcmuTv8qmu1ayGiQ8',
    appId: '1:671878337704:ios:0f43506b02de3f029e5e9d',
    messagingSenderId: '671878337704',
    projectId: 'travel-list-29',
    storageBucket: 'travel-list-29.appspot.com',
    iosBundleId: 'com.example.travelList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwFp-phHGegV8pR1xcmuTv8qmu1ayGiQ8',
    appId: '1:671878337704:ios:0f43506b02de3f029e5e9d',
    messagingSenderId: '671878337704',
    projectId: 'travel-list-29',
    storageBucket: 'travel-list-29.appspot.com',
    iosBundleId: 'com.example.travelList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAPllxW76PdarRjm74Yy96rrvOHzILx_A',
    appId: '1:671878337704:web:5c0408359e7740349e5e9d',
    messagingSenderId: '671878337704',
    projectId: 'travel-list-29',
    authDomain: 'travel-list-29.firebaseapp.com',
    storageBucket: 'travel-list-29.appspot.com',
    measurementId: 'G-35BLQZCSE5',
  );

}